### ISSUE TITLE
[Steam Trailers, Steam Screenshots] Some games do not load trailers or screenshots from Steam (Even with Steam linked and a trailer on the Steam page)

### ISSUE THREAD

**Issue by PaulTheCarman** [darklinkpower/PlayniteExtensionsCollection#571]
### Extension name

Steam Trailers and Steam Screenshots

### Bug Description

Some games don't appear to load trailers from Steam. From what I've gathered, the extension uses the Steam link to stream the trailer from the Steam store page, but some games, despite being able to load screenshots for said game, do not load the trailer. And it's not because the game doesn't have a trailer either.

I've identified six games in my library that have a trailer on Steam, are able to load screenshots for the game via Steam Screenshots, but aren't able to load the trailer:

- Batman: Arkham Asylum Game of the Year Edition
- Metro 2033
- Resident Evil: Revelations
- Lego Indiana Jones 2
- Lara Croft and the Guardian of Light
- Sid Meier's Civilization V

As I said, all six of those games are able to load screenshots via Steam Screenshots, but even that's not always the case. Borderlands 2 doesn't seem to load either a trailer or screenshots, though this is the only game I have found that has this behavior. 

A workaround is to simply download these trailers and set them as the video trailer, of course, and to download the screenshots manually and display them using Screenshot Viewer - both of which I've already done. But I'd prefer to simply stream it from Steam to save storage. All these files can add up over time.

In the screenshot I've attached, using Sid Meier's Civilization V as an example, you can see that I have a correct Steam page linked, since it has loaded the "Steam Screenshots" tab. However, the video is not playing. If you navigate to the Steam page for this game, the game has a trailer in the first slot.

### Logs

[extensions.log](https://github.com/user-attachments/files/16970638/extensions.log)
[playnite.log](https://github.com/user-attachments/files/16970639/playnite.log)

### Screenshots

![Desktop Screenshot 2024 09 11 - 17 33 17 16](https://github.com/user-attachments/assets/2cf16370-2d20-42b8-b212-e6d8ecda6c9d)

**Comment by darklinkpower** [comment]
It looks like the video is being correctly set but there's an issue in the Windows Media Player in your system, which is used to play the videos. Please check this troubleshooting page: https://github.com/darklinkpower/PlayniteExtensionsCollection/wiki/Extra-Metadata-Loader#videos-are-not-playing

**Comment by PaulTheCarman** [comment]
Thanks for the reply. I followed the troubleshooting guide, and the boxes for Windows Media Player are already ticked. I have a library of over 1,000 games, and virtually every single one of them plays videos, with the exception of these select few. Also, I'm not sure how this would affect Borderlands 2, which doesn't seem to load screenshots either. Could you take a second look at this? I'm just trying to get to the bottom of the issue. Thanks!

**Comment by darklinkpower** [comment]
Can you go to the extension data folder and upload the `49520_appdetails.json` file inside `appdetails`?

![image](https://github.com/user-attachments/assets/057c6f7b-7640-47b7-a94c-d304feef2667)

I'm wondering if the response was unsuccessful or doesn't have screenshots. It's downloaded from https://store.steampowered.com/api/appdetails?appids=49520

![image](https://github.com/user-attachments/assets/a9191319-189e-42e9-adf1-cce508afb642)

It's working correctly for me for some reason:

![image](https://github.com/user-attachments/assets/5c64b4ae-56cf-4062-8072-2a87a1acdd8a)

Perhaps it's the same issue as #550

**Comment by PaulTheCarman** [comment]
[49520_appdetails.json](https://github.com/user-attachments/files/17000792/49520_appdetails.json)

I've attached the 49520_appdetails file, but I'll save you a few clicks. The file just says:

{"49520":{"success":false}}

That's all. I've also attached a screenshot showing the Steam link.
![Desktop Screenshot 2024 09 13 - 23 38 06 93](https://github.com/user-attachments/assets/f2cc8f7c-92fb-474d-99ca-a1131a8a975d)

Just out of curiosity, if you add any of the games I mentioned, does the trailer load for you?

**Comment by darklinkpower** [comment]
> 
I've attached the 49520_appdetails file, but I'll save you a few clicks. The file just says:

> {"49520":{"success":false}}

Yeah it's the same issue then as the other issue I linked, no idea why Steam returns unsuccessful data but I have published a new update a few minutes ago that fixes this issue for the Steam Screenshots extension. I've been rewriting the Extra Metadata extension and will also implement this fix there but I can't say when I'll finish it. Can you check if the file downloaded by ExtraMetadataLoader also says success:false?

The file is the game id found in the Edit window:

![image](https://github.com/user-attachments/assets/475162e2-62ca-4de3-9579-91d14a02c1c3)

![image](https://github.com/user-attachments/assets/f60ebaaf-2908-4d47-af91-8cc7de62ecdf)

> Just out of curiosity, if you add any of the games I mentioned, does the trailer load for you?

It's working fine for me when streaming, both in normal and high quality:

![image](https://github.com/user-attachments/assets/6727323b-0d12-4b9a-82ab-616c31e9a50f)

**Comment by PaulTheCarman** [comment]
Wow you've already pushed an update? Mad respect.

I checked the Extra Metadata Loader file and it also says success:false. So I deleted it and lo and behold, the trailer loads now. Thanks so much for that!

However, I tried doing the same exact thing with Batman: Arkham Asylum Game of the Year Edition and the trailer still does not load. I've attached the file for you. This one actually has content within it.

[1779d984-c1a0-4d20-89ca-21d658392b1d_SteamAppDetails.json](https://github.com/user-attachments/files/17000933/1779d984-c1a0-4d20-89ca-21d658392b1d_SteamAppDetails.json)

**Comment by Cszyn** [comment]
Hello, after a recent reinstallation of windows this accused to me as well except all the games are now effected
![Playnite DesktopApp_5xg2PPLNoq](https://github.com/user-attachments/assets/f5d63dd4-17ae-4671-b7c7-63d310eae81a)

![Playnite DesktopApp_FPxqxKkJY6](https://github.com/user-attachments/assets/adecd912-3dd8-4520-90bb-d794c0ac03fd)

![Playnite DesktopApp_NyFFK77eAe](https://github.com/user-attachments/assets/993625fc-eaec-492f-91fb-f4f1a181c3ba)

**Comment by Cszyn** [comment]
> Hello, after a recent reinstallation of windows this accused to me as well except all the games are now effected ![Playnite DesktopApp_5xg2PPLNoq](https://private-user-images.githubusercontent.com/147027531/369118304-f5d63dd4-17ae-4671-b7c7-63d310eae81a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3NzQ5MTgsIm5iZiI6MTcyNjc3NDYxOCwicGF0aCI6Ii8xNDcwMjc1MzEvMzY5MTE4MzA0LWY1ZDYzZGQ0LTE3YWUtNDY3MS1iN2M3LTYzZDMxMGVhZTgxYS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOVQxOTM2NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jODBkMmRkM2JjYTVlMDA0ZDQ0MDE4YzA4N2MyMjIzYWU2NGE1NzU3ODU5MmE1YjhiZDg0ZjZhM2YwZDlmMDcwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.o5QaFJQ2Rb9X8u_mppKBUS9iKhstj6ZOmA4BZ9-Q8RQ)
> 
> ![Playnite DesktopApp_FPxqxKkJY6](https://private-user-images.githubusercontent.com/147027531/369118361-adecd912-3dd8-4520-90bb-d794c0ac03fd.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3NzQ5MTgsIm5iZiI6MTcyNjc3NDYxOCwicGF0aCI6Ii8xNDcwMjc1MzEvMzY5MTE4MzYxLWFkZWNkOTEyLTNkZDgtNDUyMC05MGJiLWQ3OTRjMGFjMDNmZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOVQxOTM2NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMTA4MDEzMDJjYjE4MzMyZDQyNzc3OThjM2I5NGVmZGI2MjRhOTA1ZDIwMzJlYTE3OThlZjAxNGU3ZWY1MzU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.m2jbSg8_n76ZcRNBIFToulx_On39DX5d0mvGGkSlilI)
> 
> ![Playnite DesktopApp_NyFFK77eAe](https://private-user-images.githubusercontent.com/147027531/369118448-993625fc-eaec-492f-91fb-f4f1a181c3ba.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3NzQ5MTgsIm5iZiI6MTcyNjc3NDYxOCwicGF0aCI6Ii8xNDcwMjc1MzEvMzY5MTE4NDQ4LTk5MzYyNWZjLWVhZWMtNDkyZi05MWZiLWY0ZjFhMTgxYzNiYS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOVQxOTM2NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZTM3M2EzNDEzM2MwYWJiMDg5ZDJmOTYyMTM0ODI4M2ZmMDA4MDc3NzM2MmZlMzA4OTBmZDEyODgyOTA3MGRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JtJwjsNNCgSoIWO8R16bmhcTFxH4G_Tpj66pR41noMg)

But screenshots work fine, only video is affected
